---
functional:
  - Пользователь должен иметь возможность проходить регистрацию и авторизоваться на сайте
  - Пользователю должна быть предоставлена возможность изменять данные своего профиля
  - Пользователь должен иметь возможность выбирать ИИ-противника для проведения боя
  - Пользователь должен иметь возможность вступить в бой против другого пользователя
  - Пользователь может просматривать список активных, завершенных и предстоящих турниров
  - Система должна предоставлять пользователю возможность писать и редактировать программный код на выбранном языке в рамках игрового процесса
  - На сайте реализована таблица лидеров с отображением достижений других пользователей
  - В процессе игры предусмотрена возможность взаимодействия с противником через чат, а также функции капитуляции и перезапуска сессии
  - Пользователи имеют доступ к функционалу просмотра и создания новых игровых заданий
non-functional:
  - Сайт должен быть разработан с учетом удобства использования и оптимизирован для скорости работы
  - Сайт должен быть протестирован на совместимость с последними версиями браузеров
  - Сайт должен быть способен обрабатывать большое количество трафика (например, 1000 одновременных пользователей)
  - Сайт должен быть удобным на мобильном устройстве
implicit:
  - Игра должна автоматически сохранять текущее состояние пользователя
  - Пользовательский код должен исполняться в безопасной, изолированной среде
  - Сайт должен фильтровать и модерировать задания и чат
  - Система должна вести журнал действий пользователей (например, вход в систему, отправка кода, чат), чтобы обеспечивать анализ и безопасность
