---
functional:
  - Пользователь должен иметь возможность проходить регистрацию и авторизоваться на сайте
  - Пользователь должен иметь возможность входить через социальные сети
  - Пользователю должна быть предоставлена возможность изменять данные своего профиля
  - Пользователь должен иметь возможность выбирать ИИ-противника для проведения боя
  - Пользователь должен иметь возможность вступить в бой против другого пользователя, а также приглашать любого пользователя по ссылке для начала боя
  - Пользователь может открыть страницу турниров и просматривать список предстоящих, активных и завершенных турниров
  - Система должна предоставлять пользователю возможность писать и редактировать программный код на выбранном языке в рамках игрового процесса
  - На сайте реализована таблица лидеров с отображением достижений других пользователей
  - В процессе игры предусмотрена возможность взаимодействия с противником через чат, а также функции капитуляции и перезапуска сессии
  - Пользователи имеют доступ к функционалу просмотра и создания новых игровых заданий
  - Система должна предоставлять возможность выбора уровня сложности задачи перед началом игры
  - Система должна автоматически проверять решение игрока с помощью набора тестов
  - Пользователь может просматривать историю своих игр с результатами и кодом
  - Система должна предоставлять возможность смены языка программирования в рамках игрового процесса
  - Пользователь должен иметь возможность вступать в кланы и взаимодействовать с другими участниками клана
  - Платформа должна предоставлять лобби с отображением активных игр, турниров, общего чата и списка онлайн-пользователей
non-functional:
  - Сайт должен быть разработан с учетом удобства использования и оптимизирован для скорости работы
  - Сайт должен быть протестирован на совместимость с последними версиями браузеров
  - Сайт должен быть способен обрабатывать большое количество трафика (например, 1000 одновременных пользователей)
  - Сайт должен быть удобным на мобильном устройстве
implicit:
  - Игра должна автоматически сохранять текущее состояние пользователя
  - Пользовательский код должен исполняться в безопасной, изолированной среде
  - Сайт должен фильтровать и модерировать задания и чат
  - Система должна вести журнал действий пользователей (например, вход в систему, отправка кода, чат), чтобы обеспечивать анализ и безопасность
